testing: enable Crucible in FPR
tanty/mesa-resources pull request #1
Opened 2018-03-28 16:51 UTC by jasuarez

Add support for running crucible testsuite in full-piglit-run.sh script

2018-04-25 13:16 UTC, tanty requested changes
Other than the comment inline, LGTM.

2018-04-25 13:16 UTC, tanty commented on testing/full-piglit-run.sh
> +  --crucible-prefix <prefix>       <prefix> to use with the dEQP GLES3.1 run
The usage documentation seems wrong.

2018-04-25 13:52 UTC, jasuarez commented
Changes done

2018-04-27 11:17 UTC, tanty requested changes

2018-04-27 11:17 UTC, tanty commented on testing/full-piglit-run.sh
> +  --deqp-gles31-prefix <prefix>    <prefix> to use with the crucible run
You have swapped the documentation incorrectly. Please fix this.

Additionally, you can just force pull the commit and have 1 single commit, and not 2 (or 3).

2018-04-30 11:58 UTC, jasuarez commented
Pushed again with the fix.

2018-05-02 11:40 UTC, tanty approved these changes

2018-05-02 11:41 UTC, merged

2018-05-02 11:41 UTC, tanty commented
LGTM

:+1: